### ISSUE TITLE
关于归档页面

### ISSUE THREAD

**Issue by DesertsP** [GallenHu/hexo-theme-Daily#1]
Hi !

感谢你制作的这款主题，以前我用WP就很喜欢这个设计，当时从别人的博客扒皮就是这款，（可能他因为某些原因博主去掉了版权，我误以为是他的原创设计，还专门发邮件过去征得同意）。

由于我没有任何前端功底，所以只能做些“寻章摘句”的修改。

现在能在hexo用这款主题十分高兴，但由于强迫症，有些不满足的地方，在此冒昧的提出来，希望你有时间继续完善优化。

一个是导航栏的字体，我自己搞了一个；还有底部的搜索栏，我把按钮去掉了显得整齐点；还有归档页面，我觉得NexT这款主题的归档页设计很好，不知能否借鉴改进Daily主题。

谢谢！

**Comment by glenhooo** [comment]
关于版权：
正在联系 WP 版原作者（其实部分还参考了 [liqi.io](http://liqi.io/) 这个站）

 关于UI：
原谅我的渣渣审美，对字体研究不多。目前导航栏的字体是 ：`'Helvetica Neue',Helvetica,Arial,sans-serif`，如果有好的建议希望能告诉我明确的字体名称。原则是在 Mac 和 Windows 下无论**中英文**都看着顺眼。
搜索按钮去掉后看起来应该还不错 :100:  

关于归档：
Daily主题本来是没有归档页面的，我又不想使用跟首页一样的排版，苦于没有设计经验，所以现在仅仅简单地列出了所有文章。后面会改进下归档和标签页的，也会参考Next主题的归档。

谢谢你建议，我会继续优化的。也欢迎提PR帮助改进

**Comment by glenhooo** [comment]
已更新
