### ISSUE TITLE
主题建议

### ISSUE THREAD

**Issue by quanoc** [GallenHu/hexo-theme-Daily#10]
比较喜欢daily主题，但是文章页面显示的有些窄个人觉得。建议可以加宽一点

**Comment by glenhooo** [comment]
每个人觉得合适的宽度可能不同，提供修改方法：
在项目的 `themes/Daily/source/css` 文件夹下，编辑文件 `_variables.scss`，找到 `$container-width` 一行，将600px的宽度改为你想要的宽度，如1000px，保存并重新生成即可看到效果。

**Comment by quanoc** [comment]
嗯，谢谢
