### ISSUE TITLE
How can I add a new page to the navigation bar?

### ISSUE THREAD

**Issue by mark-myzhao** [GallenHu/hexo-theme-Daily#18]
Thank you for provide this clean and elegant themes.

But I wander how can I add new pages such as `about` page to the navigation bar?
Just like this:

<img width="249" alt="screen shot 2017-04-25 at 10 05 43 am" src="https://cloud.githubusercontent.com/assets/13463626/25365935/c9b6dbfc-299e-11e7-8c43-3401eda46be4.png">

Should I add something to the theme?
And how can I route to `mysite.com/newpage` with certain ejs files?

**Comment by glenhooo** [comment]
> how can I add new pages such as `about` page?

Run `hexo new page Your_Page_Name`, and you can get a new folder（your new page） in the `source` folder.

More: https://hexo.io/zh-cn/docs/writing.html

> add to the navigation bar?

Checkout this doc: [How to customize the navigation bar ?](https://github.com/GallenHu/hexo-theme-Daily/wiki/navigation_%E5%AF%BC%E8%88%AA%E6%A0%8F)

**Comment by mark-myzhao** [comment]
Thanks a lot! That works~
