### ISSUE TITLE
博客网站CSS样式丢失。

### ISSUE THREAD

**Issue by zhishengzhang** [GallenHu/hexo-theme-Daily#2]
hexo版本信息请查看附件。
![tm](https://cloud.githubusercontent.com/assets/8622157/18743283/e7ac0482-80ea-11e6-8224-b3fb3db51288.png)
![tm 1](https://cloud.githubusercontent.com/assets/8622157/18743286/eb04be94-80ea-11e6-8e8c-4c9c38efcd93.png)

**Comment by zhishengzhang** [comment]
![tm](https://cloud.githubusercontent.com/assets/8622157/18743349/2d551168-80eb-11e6-9e46-0fd4ccc7432a.png)

**Comment by zhishengzhang** [comment]
已经解决。

**Comment by Adiwon** [comment]
你好，我想问一下这个问题你是怎么解决的？

**Comment by glenhooo** [comment]
部署在二级目录样式丢失的问题解决：

修改`_config.yml`中的`url`和`root`，可以参考demo站的配置 
https://github.com/Hinpc/Daily/blob/master/_config.yml#L15
