### ISSUE TITLE
deploy之后样式不生效？

### ISSUE THREAD

**Issue by Junior2Ran** [GallenHu/hexo-theme-Daily#21]
本地预览样式正常，deploy之后没有任何样式，是不是sass没有编译？
应该做什么操作吗？

**Comment by glenhooo** [comment]
看看浏览器控制台有什么报错信息呢？会不会有样式文件路径加载不对？

**Comment by glenhooo** [comment]
我本地使用`hexo generate`是正常显示样式的，有问题可以带上截图方便定位
