### ISSUE TITLE
How do I remove date from page?

### ISSUE THREAD

**Issue by easybeau** [GallenHu/hexo-theme-Daily#28]
Hi, 

Thank you for your beautiful theme!

My question is in the title : How do I remove date from pages but not from posts? 
Should I create a new page.ejs and remove :
`<p class="posted-on">
          <%= page.date.format(config.date_format) %>
          </p>`

Thanks for your answer.
Regards

**Comment by sgc109** [comment]
Did you find a solution?

**Comment by easybeau** [comment]
Hi, actually no. I moved to an other static site generator.

Best
