### ISSUE TITLE
请问tag的支持是否不完整？

### ISSUE THREAD

**Issue by peterpanzsy** [GallenHu/hexo-theme-Daily#29]
配置了tag，但是生成的网页并没有tag分类，如图
![image](https://user-images.githubusercontent.com/5291999/53739695-595d1100-3ecd-11e9-8b66-fca56fa7cb64.png)

**Comment by glenhooo** [comment]
文章的 tag 设置示例可以参考这里： https://github.com/Hinpc/Daily/tree/master/source/_posts
效果： http://gallenhu.coding.me/Daily/2017/09/hexo-renderer-sass-install-in-china/
