### ISSUE TITLE
归档排序有问题

### ISSUE THREAD

**Issue by SportPlusX** [GallenHu/hexo-theme-Daily#4]
例如：从上到下
2016-3-10
2016-5-10
2016-4-10
2016-3-10
2016-3-10
2016-3-10
2016-2-10
2016-1-10
2016-9-10
2016-8-10
2016-7-10

**Comment by glenhooo** [comment]
@bpplpp  感谢指出，已修正  see 4445b613b9e6294d6549f887b295446bf39cfed6
