### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by kulley** [GallenHu/hexo-theme-Daily#6]
如何设置的：
在首页显示图片，进入文章之后图片不显示？

**Comment by glenhooo** [comment]
https://github.com/GallenHu/hexo-theme-Daily/wiki/Hexo-Post-template

**Comment by gesturepotter** [comment]
对啊，为什么不在主题里预设好呢？

**Comment by glenhooo** [comment]
@gesturepotter  不太懂你所说的在主题里预设好的意思。。

如果说"在首页显示图片，进入文章之后图片不显示"这个功能，**主题本身就支持的。**不需要装额外的插件，也不需要在_config.yml里面进行配置。

实现的方法是，在你写文章或者page的时候，在md文档头部加上`photos`属性，这样的话photos就会仅在首页显示。毕竟主题是不可能帮你把文章和页面也完全写入，这里的属性肯定需要自己填写的。

如果想要内容里也显示图片，则按照正常写文章的流程，用markdown语言( `![img](imgurl)` )来添加

**Comment by gesturepotter** [comment]
明白了，非常感谢！

**Comment by gesturepotter** [comment]
还有个问题，我插入了秒拍的视频，但只能在PC端播放，移动端（chrome）没显示视频，插入youtube倒是两端都能播放。想问，怎么插入视频(秒拍、优酷)，才能适配在移动端播放呢？谢谢！
