### ISSUE TITLE
No logo image when opening post

### ISSUE THREAD

**Issue by Prochitaem** [GallenHu/hexo-theme-Daily#7]
Hi, I run into the following issue: 
image specified in logo: tag is visible only on the main page. 
When I open any post logo image is not found. Where it should be placed?

**Comment by glenhooo** [comment]
Hi, @Prochitaem 
Maybe u wrote a a relative path for your logo. My logo config is:
 `logo: /img/2016/20160807-hi-logo.svg`
Take notice of the first  `/`  in logo url, maybe u lost it, so it would query the image in a relative path.
And I place my logo image in this folder:
`/source/img/2016/`

My config file: https://github.com/Hinpc/hexo-blog-generator/blob/master/_config.yml#L74

If still not work, can u paste your `_config.yml` content ?

**Comment by Prochitaem** [comment]
Thanks! Issue is solved.

**Comment by Prochitaem** [comment]
Hi again, this issue is also image-related, so I desided to just reopen this issue.
The poroblem is with featured image. In your blog [sample ](https://blog.hinpc.com/) featured images are working just fine. In my blog they do not appear. Do I miss something? (using featured-image plugin)

**Comment by glenhooo** [comment]
Do you mean the image in the home page?
Daily Theme will do it with no need for  the featured-image plugin.
Use attribute: `photos`  in the front-matter of your post.
Example:  https://github.com/GallenHu/hexo-theme-Daily/wiki/Hexo-Post-template#%E6%96%87%E7%AB%A0%E6%A8%A1%E6%9D%BF

The image will show in the home page, and not show in the post content.
If you want to show any image in the content, just use (`![img](imgurl)`)

**Comment by GallenHu** [comment]
#6

**Comment by Prochitaem** [comment]
Yes, that is exactly I was looking for! Thanks for your assistance!

**Comment by chrisnovak** [comment]
For the post images on the home page, is there any way to access them relative to the path?

E.g.: ``photos: "{{% asset_img "asset.jpg" %}}"``

instead of 

``photos: /2016/12/12/test-post/asset.jpg``

Thanks!

**Comment by glenhooo** [comment]
@chrisnovak 
You mean use variables in the path ? It is not supported, beacause HEXO use markdown(.md) file and md file cannot recognize variables. 
Maybe you can edit my source code in the file `article-index.ejs` to achieve your purpose.
